blank_issues_enabled: false
contact_links:
  - name: Consul Community Support
    url: https://discuss.hashicorp.com/c/consul/29
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help.\n Happy Coding!
